# -*- coding: utf-8 -*-
"""STYLE HUB AI Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzHYnocfa1lA-vdZVDYrRXJt6org2Jgt
"""

!pip install fastapi uvicorn google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pymupdf python-docx sentence-transformers faiss-cpu groq python-dotenv pyngrok nest-asyncio

from google.colab import drive
drive.mount('/content/drive')

import fitz
import docx
import io
import re

def extract_text_from_docx(file_path):
    doc = docx.Document(file_path)
    text = ""
    for para in doc.paragraphs:
        text += para.text + "\n"
    return text

def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def chunk_text(text, chunk_size=500, overlap=50):
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = start + chunk_size
        chunk = ' '.join(words[start:end])
        chunks.append(chunk)
        start = end - overlap
    return chunks

drive_path = '/content/drive/MyDrive'
docx_files = ['dress_catalog.docx', 'company_policy.docx',
              'order_status.docx', 'delivery_policy.docx',
              'complaint_policy.docx', 'shop_timing_contact.docx']

all_chunks = []
for file_name in docx_files:
    file_path = os.path.join(drive_path, file_name)
    text = extract_text_from_docx(file_path)
    text = clean_text(text)
    chunks = chunk_text(text)
    for i, chunk in enumerate(chunks):
        all_chunks.append({
            'chunk_text': chunk,
            'metadata': {
                'file_name': file_name,
                'chunk_index': i,
                'source': 'gdrive'
            }
        })
    print(f"✅ {file_name} → {len(chunks)} chunks")

print(f"\nTotal chunks: {len(all_chunks)}")

from sentence_transformers import SentenceTransformer
import numpy as np

print("Loading embedding model...")
model = SentenceTransformer('all-MiniLM-L6-v2')

texts = [chunk['chunk_text'] for chunk in all_chunks]
print(f"Generating embeddings for {len(texts)} chunks...")

embeddings = model.encode(texts, batch_size=32, show_progress_bar=True)

for i, chunk in enumerate(all_chunks):
    chunk['embedding'] = embeddings[i].tolist()

print(f"✅ Embeddings generated! Shape: {embeddings.shape}")

import faiss
import pickle
import numpy as np

embeddings_array = np.array([chunk['embedding'] for chunk in all_chunks]).astype('float32')
texts = [chunk['chunk_text'] for chunk in all_chunks]
metadata = [chunk['metadata'] for chunk in all_chunks]

dimension = embeddings_array.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings_array)

faiss.write_index(index, '/content/faiss_index.bin')
with open('/content/metadata.pkl', 'wb') as f:
    pickle.dump({'texts': texts, 'metadata': metadata}, f)

print(f"✅ FAISS index created with {index.ntotal} chunks!")

import os
from groq import Groq
import faiss
import pickle
import numpy as np

# Load FAISS
index = faiss.read_index('/content/faiss_index.bin')
with open('/content/metadata.pkl', 'rb') as f:
    store = pickle.load(f)

GROQ_API_KEY = ""
client = Groq(api_key=GROQ_API_KEY)

def ask(query):
    query_embedding = model.encode(query).tolist()
    query_array = np.array([query_embedding]).astype('float32')

    distances, indices = index.search(query_array, 5)

    results = []
    for idx in indices[0]:
        if idx != -1:
            results.append(store['texts'][idx])

    context = "\n\n".join(results)
    sources = list(set([store['metadata'][idx]['file_name'] for idx in indices[0] if idx != -1]))

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "Answer questions based only on the provided context."},
            {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {query}"}
        ]
    )

    return {
        "answer": response.choices[0].message.content,
        "sources": sources
    }

# Test
result = ask("What is the return policy?")
print("Answer:", result['answer'])
print("Sources:", result['sources'])

embeddings = model.encode(
    [chunk['chunk_text'] for chunk in all_chunks],
    batch_size=32,
    show_progress_bar=True
)
for i, chunk in enumerate(all_chunks):
    chunk['embedding'] = embeddings[i].tolist()
print(f"✅ Embeddings done: {embeddings.shape}")

import faiss
import pickle
import numpy as np

embeddings_array = np.array([chunk['embedding'] for chunk in all_chunks]).astype('float32')
texts = [chunk['chunk_text'] for chunk in all_chunks]
metadata = [chunk['metadata'] for chunk in all_chunks]

dimension = embeddings_array.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings_array)

faiss.write_index(index, '/content/faiss_index.bin')
with open('/content/metadata.pkl', 'wb') as f:
    pickle.dump({'texts': texts, 'metadata': metadata}, f)

print(f"✅ FAISS updated with {index.ntotal} chunks!")

import docx
import re
import os

def extract_table_text(file_path):
    doc = docx.Document(file_path)
    text = ""
    for para in doc.paragraphs:
        text += para.text + "\n"
    for table in doc.tables:
        for row in table.rows:
            row_text = " | ".join([cell.text.strip() for cell in row.cells])
            text += row_text + "\n"
    return text

def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def chunk_text(text, chunk_size=200, overlap=30):
    words = text.split()
    chunks = []
    start = 0
    while start < len(words):
        end = start + chunk_size
        chunk = ' '.join(words[start:end])
        chunks.append(chunk)
        start = end - overlap
    return chunks

drive_path = '/content/drive/MyDrive'
all_chunks = []

files = [
    'dress_catalog.docx',
    'company_policy.docx',
    'order_status.docx',
    'delivery_policy.docx',
    'complaint_policy.docx',
    'shop_timing_contact.docx'
]

for file_name in files:
    file_path = f"{drive_path}/{file_name}"
    text = extract_table_text(file_path)
    text = clean_text(text)
    chunks = chunk_text(text)
    for i, chunk in enumerate(chunks):
        all_chunks.append({
            'chunk_text': chunk,
            'metadata': {
                'file_name': file_name,
                'chunk_index': i,
                'source': 'gdrive'
            }
        })
    print(f"✅ {file_name} → {len(chunks)} chunks")

print(f"\nTotal chunks: {len(all_chunks)}")

# Embeddings
embeddings = model.encode(
    [chunk['chunk_text'] for chunk in all_chunks],
    batch_size=32,
    show_progress_bar=True
)
for i, chunk in enumerate(all_chunks):
    chunk['embedding'] = embeddings[i].tolist()
print(f"✅ Embeddings done: {embeddings.shape}")

# FAISS Save
import faiss
import pickle
import numpy as np

embeddings_array = np.array([chunk['embedding'] for chunk in all_chunks]).astype('float32')
texts = [chunk['chunk_text'] for chunk in all_chunks]
metadata = [chunk['metadata'] for chunk in all_chunks]

dimension = embeddings_array.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(embeddings_array)

faiss.write_index(index, '/content/faiss_index.bin')
with open('/content/metadata.pkl', 'wb') as f:
    pickle.dump({'texts': texts, 'metadata': metadata}, f)

print(f"✅ FAISS updated with {index.ntotal} chunks!")

# Reload FAISS and store
index = faiss.read_index('/content/faiss_index.bin')
with open('/content/metadata.pkl', 'rb') as f:
    store = pickle.load(f)

print(f"✅ Reloaded! Total chunks: {index.ntotal}")

# Test
result = ask("What is the price of Linen Saree?")
print("Answer:", result['answer'])
print("Sources:", result['sources'])

import hashlib
import json

# Cache dictionary
cache = {}

def ask_with_cache(query):

    cache_key = hashlib.md5(query.lower().strip().encode()).hexdigest()


    if cache_key in cache:
        print("✅ Cache hit!")
        return cache[cache_key]


    print("🔍 Fetching from LLM...")
    result = ask(query)

    cache[cache_key] = result
    return result


print("First call:")
result1 = ask_with_cache("What is the return policy?")
print("Answer:", result1['answer'][:100])

print("\nSecond call (same question):")
result2 = ask_with_cache("What is the return policy?")
print("Answer:", result2['answer'][:100])

def ask_with_filter(query, file_filter=None):
    cache_key = hashlib.md5(f"{query}{file_filter}".lower().strip().encode()).hexdigest()

    if cache_key in cache:
        print("✅ Cache hit!")
        return cache[cache_key]

    query_embedding = model.encode(query).tolist()
    query_array = np.array([query_embedding]).astype('float32')

    distances, indices = index.search(query_array, 10)

    results = []
    sources = []
    for idx in indices[0]:
        if idx != -1:
            meta = store['metadata'][idx]

            if file_filter is None or meta['file_name'] == file_filter:
                results.append(store['texts'][idx])
                sources.append(meta['file_name'])

    if not results:
        return {"answer": "No relevant documents found.", "sources": []}

    context = "\n\n".join(results[:5])
    sources = list(set(sources))

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "Answer questions based only on the provided context."},
            {"role": "user", "content": f"Context:\n{context}\n\nQuestion: {query}"}
        ]
    )

    result = {
        "answer": response.choices[0].message.content,
        "sources": sources
    }
    cache[cache_key] = result
    return result

print("Without filter:")
r1 = ask_with_filter("What is the return policy?")
print("Sources:", r1['sources'])

print("\nWith filter — company_policy.docx only:")
r2 = ask_with_filter("What is the return policy?", file_filter="company_policy.docx")
print("Sources:", r2['sources'])

import asyncio
import concurrent.futures

executor = concurrent.futures.ThreadPoolExecutor(max_workers=4)

async def async_ask(query, file_filter=None):
    loop = asyncio.get_event_loop()
    result = await loop.run_in_executor(
        executor,
        lambda: ask_with_filter(query, file_filter)
    )
    return result

async def process_multiple_questions(questions):
    print(f"Processing {len(questions)} questions simultaneously...")
    tasks = [async_ask(q) for q in questions]
    results = await asyncio.gather(*tasks)
    return results

questions = [
    "What is the return policy?",
    "What are delivery charges?",
    "What is the price of Linen Saree?"
]

results = await process_multiple_questions(questions)

for q, r in zip(questions, results):
    print(f"\nQ: {q}")
    print(f"A: {r['answer'][:100]}...")

import os
import json
from datetime import datetime

SYNC_STATE_FILE = '/content/sync_state.json'

def load_sync_state():
    if os.path.exists(SYNC_STATE_FILE):
        with open(SYNC_STATE_FILE, 'r') as f:
            return json.load(f)
    return {}

def save_sync_state(state):
    with open(SYNC_STATE_FILE, 'w') as f:
        json.dump(state, f)

def incremental_sync():
    drive_path = '/content/drive/MyDrive'
    files = [
        'dress_catalog.docx',
        'company_policy.docx',
        'order_status.docx',
        'delivery_policy.docx',
        'complaint_policy.docx',
        'shop_timing_contact.docx'
    ]

    sync_state = load_sync_state()
    new_chunks = []
    updated_files = []

    for file_name in files:
        file_path = f"{drive_path}/{file_name}"
        mod_time = str(os.path.getmtime(file_path))

        # Check file
        if sync_state.get(file_name) == mod_time:
            print(f"⏭️ Skipped (no change): {file_name}")
            continue


        print(f"🔄 Syncing: {file_name}")
        text = extract_table_text(file_path)
        text = clean_text(text)
        chunks = chunk_text(text)

        for i, chunk in enumerate(chunks):
            new_chunks.append({
                'chunk_text': chunk,
                'metadata': {
                    'file_name': file_name,
                    'chunk_index': i,
                    'source': 'gdrive'
                }
            })

        sync_state[file_name] = mod_time
        updated_files.append(file_name)

    if updated_files:
        print(f"\n✅ Updated files: {updated_files}")
        save_sync_state(sync_state)
    else:
        print("\n✅ All files up to date — nothing to sync!")

    return updated_files

# First sync
print("=== First Sync ===")
incremental_sync()

print("\n=== Second Sync (no changes) ===")
incremental_sync()

import gradio as gr

def chatbot(message, history):
    result = ask(message)
    return f"{result['answer']}\n\n📄 Sources: {', '.join(result['sources'])}"

demo = gr.ChatInterface(
    fn=chatbot,
    title="👗 STYLE HUB AI Assistant",
    description="📍 Kumbakonam | 📞 9876543210 | 🕐 10AM-9PM",
    theme="soft",
    examples=[
        "What is the return policy?",
        "What are delivery charges?",
        "Do you have silk sarees?",
        "What is the exchange policy?"
    ]
)

demo.launch(share=False, inline=True)